### ISSUE TITLE
Error with cwd

### ISSUE THREAD

**Issue by XhmikosR** [sparanoid/grunt-sri-hash#2]
I just tried the latest 1.1.0 with this:

```js
sri_hash: {
    dist: {
        options: {
            algorithm: 'sha384'
        },
        expand: true,
        cwd: '<%= dirs.dest %>',
        dest: '<%= dirs.dest %>',
        src: '**/*.html'
    }
},
```

```
C:\Users\xmr\Desktop\foo>grunt sri_hash
Running "sri_hash:dist" (sri_hash) task
Reading: C:\Users\xmr\Desktop\foo\_site\2018\01\01\post\index.html
Warning: Unable to read "C:\Users\xmr\Desktop\foo\assets\css\pack.6e69b25d.css" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

The CSS file does exist in `_site/assets/css` but it seems the plugin goes one folder up than the `cwd` which is set to `_site`.

**Comment by sparanoid** [comment]
Weird, what `<%= dirs.dest %>` actually is? just pushed a possible fix for this. Could you please retest it? Thanks.

**Comment by XhmikosR** [comment]
It's looking for one folder up from the dist dir I set up there (the working dir that is), hence why the CSS isn't found.

**Comment by sparanoid** [comment]
Try adding `assetsDir` in your `Gruntfile.js`:

```js
options: {
  algorithm: 'sha384',
  assetsDir: 'base'
},
```

In your case it should be `_site`.

Sorry didn't mention it in the documentation. I'll add it later.

**Comment by XhmikosR** [comment]
Yup, that did it. It definitely needs to be documented :)

On a side note, how about making the output less verbose and show the SRI hashes etc when `--verbose` is passed? Instead show a summary by default.

**Comment by sparanoid** [comment]
See https://github.com/sparanoid/grunt-sri-hash/issues/5
